<?

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class BrandSettings
{
    private $brand_settings_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'brand_settings_add_plugin_page'));
        add_action('admin_init', array($this, 'brand_settings_page_init'));

        // Add filter to make settings available in Timber context
        add_filter('timber/context', array($this, 'add_to_context'));
    }

    public function brand_settings_add_plugin_page()
    {
        add_menu_page(
            'Brand Settings', // page_title
            'Brand Settings', // menu_title
            'manage_options', // capability
            'brand-settings', // menu_slug
            array($this, 'brand_settings_create_admin_page'), // function
            'dashicons-admin-generic', // icon_url
            2 // position
        );
    }

    // Function to add settings to Timber context
    public function add_to_context($context)
    {
        // Retrieve options from the database
        $brand_settings_options = get_option('brand_settings');

        // Add options to the Timber context
        $context['brand_settings'] = $brand_settings_options;

        return $context;
    }

    public function brand_settings_create_admin_page()
    {
        $this->brand_settings_options = get_option('brand_settings'); ?>

        <div class="wrap">
            <h2>Brand Settings</h2>
            <p>Doing All Of The Things</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('brand_settings_option_group');
                do_settings_sections('brand-settings-admin');
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function brand_settings_page_init()
    {
        register_setting(
            'brand_settings_option_group', // option_group
            'brand_settings', // option_name
            array($this, 'brand_settings_sanitize') // sanitize_callback
        );

        add_settings_section(
            'brand_settings_setting_section', // id
            'Settings', // title
            array($this, 'brand_settings_section_info'), // callback
            'brand-settings-admin' // page
        );

        add_settings_field(
            'what_is_your_name_0', // id
            'What is your name', // title
            array($this, 'what_is_your_name_0_callback'), // callback
            'brand-settings-admin', // page
            'brand_settings_setting_section' // section
        );

        add_settings_field(
            'what_is_your_favourite_colour_1', // id
            'What is your favourite colour', // title
            array($this, 'what_is_your_favourite_colour_1_callback'), // callback
            'brand-settings-admin', // page
            'brand_settings_setting_section' // section
        );

        add_settings_field(
            'what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2', // id
            'What is the average airspeed velocity of an unladen swallow', // title
            array($this, 'what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2_callback'), // callback
            'brand-settings-admin', // page
            'brand_settings_setting_section' // section
        );

        add_settings_field(
            'do_you_agree_3', // id
            'do you agree?', // title
            array($this, 'do_you_agree_3_callback'), // callback
            'brand-settings-admin', // page
            'brand_settings_setting_section' // section
        );

        add_settings_field(
            'oh_my_another_one_4', // id
            'Oh my another one', // title
            array($this, 'oh_my_another_one_4_callback'), // callback
            'brand-settings-admin', // page
            'brand_settings_setting_section' // section
        );
    }

    public function brand_settings_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['what_is_your_name_0'])) {
            $sanitary_values['what_is_your_name_0'] = sanitize_text_field($input['what_is_your_name_0']);
        }

        if (isset($input['what_is_your_favourite_colour_1'])) {
            $sanitary_values['what_is_your_favourite_colour_1'] = esc_textarea($input['what_is_your_favourite_colour_1']);
        }

        if (isset($input['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2'])) {
            $sanitary_values['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2'] = $input['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2'];
        }

        if (isset($input['do_you_agree_3'])) {
            $sanitary_values['do_you_agree_3'] = $input['do_you_agree_3'];
        }

        if (isset($input['oh_my_another_one_4'])) {
            $sanitary_values['oh_my_another_one_4'] = $input['oh_my_another_one_4'];
        }

        return $sanitary_values;
    }

    public function brand_settings_section_info()
    {
    }

    public function what_is_your_name_0_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="brand_settings[what_is_your_name_0]" id="what_is_your_name_0" value="%s">',
            isset($this->brand_settings_options['what_is_your_name_0']) ? esc_attr($this->brand_settings_options['what_is_your_name_0']) : ''
        );
    }

    public function what_is_your_favourite_colour_1_callback()
    {
        printf(
            '<textarea class="large-text" rows="5" name="brand_settings[what_is_your_favourite_colour_1]" id="what_is_your_favourite_colour_1">%s</textarea>',
            isset($this->brand_settings_options['what_is_your_favourite_colour_1']) ? esc_attr($this->brand_settings_options['what_is_your_favourite_colour_1']) : ''
        );
    }

    public function what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2_callback()
    {
    ?> <select name="brand_settings[what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2]" id="what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2">
            <?php $selected = (isset($this->brand_settings_options['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2']) && $this->brand_settings_options['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2'] === 'option-one') ? 'selected' : ''; ?>
            <option value="option-one" <?php echo $selected; ?>> Option One</option>
            <?php $selected = (isset($this->brand_settings_options['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2']) && $this->brand_settings_options['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2'] === 'value') ? 'selected' : ''; ?>
            <option value="value" <?php echo $selected; ?>>Label</option>
        </select> <?php
                }

                public function do_you_agree_3_callback()
                {
                    printf(
                        '<input type="checkbox" name="brand_settings[do_you_agree_3]" id="do_you_agree_3" value="do_you_agree_3" %s>',
                        (isset($this->brand_settings_options['do_you_agree_3']) && $this->brand_settings_options['do_you_agree_3'] === 'do_you_agree_3') ? 'checked' : ''
                    );
                }

                public function oh_my_another_one_4_callback()
                {
                    ?> <fieldset><?php $checked = (isset($this->brand_settings_options['oh_my_another_one_4']) && $this->brand_settings_options['oh_my_another_one_4'] === 'option-one') ? 'checked' : ''; ?>
            <label for="oh_my_another_one_4-0"><input type="radio" name="brand_settings[oh_my_another_one_4]" id="oh_my_another_one_4-0" value="option-one" <?php echo $checked; ?>> Option One</label><br>
            <?php $checked = (isset($this->brand_settings_options['oh_my_another_one_4']) && $this->brand_settings_options['oh_my_another_one_4'] === 'value') ? 'checked' : ''; ?>
            <label for="oh_my_another_one_4-1"><input type="radio" name="brand_settings[oh_my_another_one_4]" id="oh_my_another_one_4-1" value="value" <?php echo $checked; ?>> Label</label>
        </fieldset> <?php
                }
            }
            if (is_admin())
                $brand_settings = new BrandSettings();

            // Add the Timber context filter if Timber is activated
            if (class_exists('Timber')) {
                add_filter('timber/context', 'add_brand_settings_to_timber_context');
            }

            // Function to add settings to Timber context
            function add_brand_settings_to_timber_context($context)
            {
                // Retrieve options from the database
                $brand_settings_options = get_option('brand_settings');

                // Add options to the Timber context
                $context['brand_settings'] = $brand_settings_options;

                return $context;
            }

/* 
 * Access this value in PHP files with:
 * $brand_settings_options = get_option( 'brand_settings' ); // Array of All Options
 * $what_is_your_name_0 = $brand_settings_options['what_is_your_name_0']; // What is your name
 * $what_is_your_favourite_colour_1 = $brand_settings_options['what_is_your_favourite_colour_1']; // What is your favourite colour
 * $what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2 = $brand_settings_options['what_is_the_average_airspeed_velocity_of_an_unladen_swallow_2']; // What is the average airspeed velocity of an unladen swallow
 * $do_you_agree_3 = $brand_settings_options['do_you_agree_3']; // do you agree?
 * $oh_my_another_one_4 = $brand_settings_options['oh_my_another_one_4']; // Oh my another one
 */

//  Access these valuse in twig files like so
//   {{ brand_settings.what_is_your_name_0 }}, {{ brand_settings.what_is_your_favourite_colour_1 }}